[rf]
freq_offset = 0
tx_gain = 50
rx_gain = 40
srate = 23.04e6
nof_antennas = 1

device_name = zmq
device_args = tx_port=tcp://UE_IP:2001,rx_port=tcp://gNB_IP:2000,base_srate=23.04e6

[rat.eutra]
dl_earfcn = 2850
nof_carriers = 0

[rat.nr]
bands = 3
nof_carriers = 1
max_nof_prb = 106
nof_prb = 106

[pcap]
enable = none
mac_filename = /tmp/ue_with_mbs_mac.pcap
mac_nr_filename = /tmp/ue_with_mbs_mac_nr.pcap
nas_filename = /tmp/ue_with_mbs_nas.pcap

[log]
all_level = info
phy_lib_level = none
all_hex_limit = 32
filename = /tmp/ue_with_mbs.log
file_max_size = -1

[usim]
mode = soft
algo = milenage
opc  = 00000000000000000000000000000000
k    = 00000000000000000000000000000000
imsi = 999701234567891
imei = 353490069873319

[rrc]
release = 15
ue_category = 4

[slicing]
enable = false
nssai-sst = 1
nssai-sd = 16777215

[nas]
apn = internet
apn_protocol = ipv4

[gw]
ip_devname = tun_srsue
ip_netmask = 255.255.255.0

[gui]
enable = false
